apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: tmi

resources:
  - 00-namespace.yaml
  - 10-postgres.yaml
  - 20-backend.yaml
  - 30-frontend.yaml
  - 40-ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: take-my-interview
